# ESTO ES UN COMENTARIO
# Todo lo que está a la derecha de # es solo para nosotros

version: 0.3.5 # NO TOCAR

# Configuración Global
html:
# title: Este valor no funciona porque esta comentado
  title: Links | Martin (Tincho) # Este es el Título que aparece en la pestaña de navegador

# Colores de plantilla
theme:
  background_color: "#f9fafb"
  # cover_color: "#ff7070"

# Configuración Central
main:
  title: Martin (Tincho) # Aca podes poner tu nombre o el de tu producto

# Lista de bloques
blocks:
  # Estos bloques los podes editar cambiando SOLO el texto que está en blanco
  # Sacale 
  - title: Github
    icon: github
    url: https://github.com/tincho70

  - title: Nostr
    icon: github
    url: https://app.coracle.social/people/npub1ptwv0m9uytzkz3k5te3y9j9k46f5r4h4ts5gdh0qzfp88qn2tgsshc2nu0
# Guardá el archivo haciendo click en Commit Changes, abajo
# Volvé a las instrucciones
